version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - backend

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${GOAPP_PORT}:${GOAPP_PORT}"
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:
    driver: bridge