version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - backend
    env_file:
      - .env

  calculation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CALCULATION_PORT}:${CALCULATION_PORT}"
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:
    driver: bridge